import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/views/NavBar";
import Sidebar from "@/views/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="bg-slate-950 text-slate-200"
    >
      <body className={inter.className}>
        <NavBar />
        <div className="flex pt-1">
          <Sidebar />
          <div className="w-full px-4 pt-7">{children}</div>
        </div>
      </body>
    </html>
  );
}
